docker環境へ移行
hisoka0620/laravel_with_vue3_tutorial pull request #16
Opened 2021-08-02 09:04 UTC by hisoka0620

2021-08-02 11:51 UTC, ysku requested changes
README.md に環境構築手順を書いてください

2021-08-02 11:53 UTC, ysku commented
`docker-compose up` を行うとこうなります
<img width="969" alt="Screen Shot 2021-08-02 at 20 52 59" src="https://user-images.githubusercontent.com/17197355/127857778-c9b2c7e5-afc0-4a0d-8909-0cf26ca0c4f4.png">

2021-08-02 11:54 UTC, ysku commented
あと `backend` ディレクトリ配下にわざわざ移動しなくても今回のようなことはできたと思いますよ

2021-08-02 11:57 UTC, ysku commented
`backend` ディレクトリで以下のコマンドを実行したのちに `docker-compose up` を実行するとこうなります
```
npm install

npm run dev
```

<img width="964" alt="Screen Shot 2021-08-02 at 20 56 54" src="https://user-images.githubusercontent.com/17197355/127858250-dff4e1ad-dc70-43d5-9865-dcf8c8db7a77.png">

2021-08-02 11:59 UTC, ysku commented
`backend` ディレクトリ配下で `touch database/database.sqlite && php artisan migrate --seed` を実行したのちにプロジェクトルートで docker-compose up で動きました

2021-08-02 12:04 UTC, ysku commented on infra/php/Dockerfile
> +WORKDIR /work
[質問] この Dockerfile でどうやって laravel が実行されるの？

2021-08-02 15:24 UTC, hisoka0620 commented on infra/php/Dockerfile
> +WORKDIR /work
ちょっとよく分かってないです。Qiitaの記事を参考にさせてもらいました。
[https://qiita.com/ucan-lab/items/56c9dc3cf2e6762672f4#%E3%82%A6%E3%82%A7%E3%83%96%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BCweb%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A%E3%82%92%E4%BD%9C%E3%82%8B](url)

2021-08-04 15:24 UTC, ysku commented on infra/php/Dockerfile
> +WORKDIR /work
ちゃんと理解して使用するようにしてください
無知は罪です

2021-08-04 15:25 UTC, ysku approved these changes
LGTM
コンフリクトの解消をお願いします

2021-08-05 14:50 UTC, merged