Test1
hisoka0620/laravel_with_vue3_tutorial pull request #2
Opened 2021-05-16 06:56 UTC by hisoka0620

task complete 機能の追加

2021-05-16 07:00 UTC, ysku commented
issue のリンクを PR の概要に貼ってください 🙏 
また issue のステータスをレビュー中に移動してください 🙏

2021-05-16 07:03 UTC, hisoka0620 commented
変更しました

2021-05-16 07:15 UTC, ysku reviewed
動作としては問題ないです！お疲れ様です
いくつかコメントしているのでそれら対応してみてください

あと PR の目的と直接関係ない変更はできるだけ含めないようにお願いします

2021-05-16 07:15 UTC, ysku commented on database/migrations/2021_04_05_042627_create_tasks_table.php
> +            $table->boolean('confirmed')->default(false);
laravel の migration では過去に実行したファイルが記録されます
こうしてしまうと、 `2021_04_05_042627_create_tasks_table.php ` はすでに実行されたものとして `php artisan migrate` が実行された時に今回の変更が反映されないので、新しく別の migration ファイルを追加してそこで confirmed のカラムの追加を行うようにしてください

2021-05-16 07:15 UTC, ysku commented on app/Http/Controllers/TaskController.php
> -	}
インデントの変更は今回の作業とは直接関係のないものなのでできればインデントの変更がないようにしてください
（ 変更が少ない方がレビューワーの負担が減ります

2021-05-16 07:15 UTC, ysku commented on public/js/app.js
> +/***/ "./node_modules/babel-loader/lib/index.js??clonedRuleSet-5.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./resources/js/components/TaskCompleteComponent.vue?vue&type=script&
このファイルは npm run prod で生成されるものなので git に含める必要はないです
git の管理下からこのファイルを除外して、 .gitignore にこのファイルを入れるようにしてみてください

2021-05-16 07:15 UTC, ysku commented on routes/api.php
> +Route::get('/tasks/complete', [TaskController::class, 'getComplete']);
`/tasks/complete` を作るのではなく、 `/tasks` のエンドポイントに `?completed=true` のようなクエリパラメータを送ると完了した task だけ返るように実装してみてください

理由としてはこのように実装しちゃうと、例えば他の条件で task を取得する際にエンドポイントを追加する必要が出て来てしまうからです

2021-05-16 07:15 UTC, ysku commented on routes/api.php
> +Route::put('/tasks/complete/{task}', [TaskController::class, 'cancelCompleted']);
これもエンドポイントを追加するのではなく、 `Route::put('/tasks/{task}'` で `complete={true,false}` をリクエストボディとして受け取れるようにしてみてください

2021-05-16 07:16 UTC, ysku commented on database/migrations/2021_04_05_042627_create_tasks_table.php
> +            $table->boolean('confirmed')->default(false);
これが参考になると思います
https://readouble.com/laravel/7.x/ja/migrations.html

2021-05-21 14:14 UTC, ysku requested changes

2021-05-21 14:14 UTC, ysku commented on app/Http/Controllers/TaskController.php
> +        }
前回指摘したここがなおってないです

2021-05-21 15:15 UTC, ysku reviewed
追加でコメントしました

2021-05-21 15:15 UTC, ysku commented on database/migrations/2021_05_21_134956_add_confirmed_to_tasks_table.php
> +            //
この部分は `$table->boolean('confirmed')->default(false);` の変更を戻す際に必要になります
`$table->boolean('confirmed')->default(false);` は confirmed というカラムを追加しているのですが、戻すためには逆に confirmed というカラムを削除する必要があります
https://laravel.com/docs/8.x/migrations#dropping-columns
を参考にこの部分を実装してみてください

2021-05-21 15:15 UTC, ysku commented on database/migrations/2021_05_21_135114_add_deadtime_to_tasks_table.php
> +<?php
このファイルはいらなそうなので取り除いてください

2021-05-21 15:15 UTC, ysku commented on database/seeders/TasksTableSeeder.php
> +                'confirmed' => 0
[nits] インデントがおかしい
( [nits の意味](https://itneko.com/lgtm/#:~:text=%E3%81%AE%E7%95%A5%E3%81%A7%E3%81%99%E3%80%82-,nits,%E3%81%AE%E8%AA%A4%E5%AD%97%E8%84%B1%E5%AD%97%E3%81%AA%E3%81%A9%E3%81%AA%E3%81%A9%E3%80%82)

2021-05-21 15:15 UTC, ysku commented on database/migrations/2021_04_05_042627_create_tasks_table.php
> +            $table->boolean('confirmed')->default(false);
これまだ修正されていないです
`database/migrations/2021_05_21_134956_add_confirmed_to_tasks_table.php` が追加されて、そこで confirmed のカラムが追加されるようになっていると思うので、この行は不要です

2021-05-21 16:17 UTC, ysku approved these changes
LGTM

2021-05-21 16:18 UTC, merged