deadline
hisoka0620/laravel_with_vue3_tutorial pull request #7
Opened 2021-05-23 09:44 UTC by hisoka0620

2021-05-23 12:37 UTC, ysku reviewed
コメントしました

2021-05-23 12:37 UTC, ysku commented on resources/js/components/TaskEditComponent.vue
> +                            v-model="getDeadline"
ここが原因です
https://qiita.com/simezi9/items/c27d69f17d2d08722b3a とか読んでみてください

2021-05-25 11:06 UTC, ysku requested changes
コメントしました
コメントへの返答と修正をお願いします

2021-05-25 11:06 UTC, ysku commented on resources/js/components/TaskCompleteComponent.vue
> +                const timezone = new Date();
`timezone` ...? `new Date();` で得られる値は現在時刻だと思うのですが、どういう意図で `timezone` と命名しました?

2021-05-25 11:06 UTC, ysku commented on resources/js/components/TaskCompleteComponent.vue
> +                if (formatNow > value) {
ここ文字列比較してますよね？ 一般的に日時を文字列を比較するのはよくないです（フォーマットが違う場合にすぐにバグるからです
Date 型同士で比較するように修正をお願いします

2021-05-25 11:06 UTC, ysku commented on resources/js/components/TaskExpiredComponent.vue
> +        }
resources/js/components/TaskCompleteComponent.vue と同じコードがありますね
どうすれば同じコードが発生しないようにできるか考えてみてください

2021-05-25 11:06 UTC, ysku commented on resources/js/components/TaskCompleteComponent.vue
> +        classObject: function() {
`classObject` という命名がよくないです、 `classObject` と言われても何をしてくれるものなのかすぐにわからないです

2021-05-25 11:06 UTC, ysku commented on resources/js/components/TaskEditComponent.vue
> -  <div class="container">
インデントの修正は本来 PR の目的と関係しないのでやめてください

2021-05-25 11:06 UTC, ysku commented on app/Http/Controllers/TaskController.php
> +        if ($completed == true) {
なぜこうしましたか？

2021-05-25 11:06 UTC, ysku commented on database/migrations/2021_05_22_055008_create_add_deadline_to_tasks.php
> +            $table->dateTime('deadline')->default(\Carbon\Carbon::now());
`default(\Carbon\Carbon::now())` だと `deadline` に値がない状態でデータベースに保存すると現在時刻が入ってしまい、そうなるとタスクを作成した時点で「終了」となってしまうとおもいます

2021-05-25 11:17 UTC, hisoka0620 commented on app/Http/Controllers/TaskController.php
> +        if ($completed == true) {
$completedにはtrueの値が入るのでtrueと比較した条件式を書きましたが今見返すと、!is_null()がbetterだと気づきました

2021-05-25 11:17 UTC, hisoka0620 commented on app/Http/Controllers/TaskController.php
> +        if ($completed == true) {
$completedにはtrueの値が入るのでtrueと比較した条件式を書きましたが今見返すと、!is_null()がbetterだと気づきました

2021-05-25 11:22 UTC, hisoka0620 commented on resources/js/components/TaskCompleteComponent.vue
> +                const timezone = new Date();
console.log(new Date());で
Tue May 25 2021 20:20:26 GMT+0900 (日本標準時)のような結果を取得したのでtimezoneに命名しました

2021-05-25 12:49 UTC, ysku commented on resources/js/components/TaskCompleteComponent.vue
> +                const timezone = new Date();
なるほど
`Tue May 25 2021 20:20:26 GMT+0900` 自体は timezone aware なものですが、ここでは "現在時刻" というのが大事なので `now` という命名でも良いと思います
( timezone aware はわからなかったら調べてみてください

2021-05-25 15:13 UTC, ysku requested changes
コメントしました

2021-05-25 15:13 UTC, ysku commented on resources/js/app.js
> +                const currentTime = moment(now).format('YYYY-MM-DD HH:mm')
`format('YYYY-MM-DD HH:mm')` を使った場合の戻り値は文字列です
関数の引数の `value` も文字列です
なので `currentTime > value` も文字列比較になっています

2021-05-25 15:13 UTC, ysku commented on resources/js/app.js
> +app.mixin(dangerMixin)
`dangerMixin` の命名... 🤔

2021-05-25 15:13 UTC, ysku commented on database/migrations/2021_05_22_055008_create_add_deadline_to_tasks.php
> +            $table->dateTime('deadline')->default(\Carbon\Carbon::now());
こちらなおっていないですが、直さなかった理由はありますか？それとも無視ですか？

2021-05-25 15:13 UTC, ysku commented on resources/js/app.js
> +            path: '/tasks?deadline=true',
<img width="261" alt="Screen Shot 2021-05-26 at 0 07 24" src="https://user-images.githubusercontent.com/17197355/119521862-7b951f00-bdb6-11eb-96ed-7d6ca77a7e29.png">
expired だけ小文字始まりになっている

2021-05-25 15:14 UTC, ysku commented on resources/js/app.js
> +app.mixin(dangerMixin)
危険な mixin みたいに思われるとおもう

2021-05-25 15:25 UTC, hisoka0620 commented on database/migrations/2021_05_22_055008_create_add_deadline_to_tasks.php
> +            $table->dateTime('deadline')->default(\Carbon\Carbon::now());
datetime-localにrequiredを追加することで空入力での登録を防ぐことで解決したつもりでしたが、それではダメなんでしょうか？

2021-05-25 15:28 UTC, ysku commented on database/migrations/2021_05_22_055008_create_add_deadline_to_tasks.php
> +            $table->dateTime('deadline')->default(\Carbon\Carbon::now());
ユーザがタスクの期限を指定せずにタスクを作成したい場合はどうしますか？

2021-05-26 14:27 UTC, ysku commented on app/Http/Controllers/TaskController.php
> +        } elseif (!is_null($deadline)) {
きれいになった 👍

2021-05-26 14:38 UTC, ysku reviewed
追加でコメントしました

2021-05-26 14:38 UTC, ysku commented on app/Http/Controllers/TaskController.php
> +            })->get();
今発行されているクエリは以下
```sql
select * from "tasks" where "confirmed" = 0 and "deadline" > ? or ("confirmed" = 0 and "deadline" is null)
```

ただ、本来欲しいのは
```sql
select * from "tasks" where "confirmed" = 0 and ("deadline" > ? or "deadline" is null)
```

sql クエリの確認の仕方
- https://qiita.com/ucan-lab/items/753cb9d3e4ceeb245341
- https://www.engilaboo.com/laravel-log-stdout/

本来欲しい SQL になるように修正してください

2021-05-26 14:42 UTC, ysku commented on database/migrations/2021_05_22_055008_create_add_deadline_to_tasks.php
> +            $table->dateTime('deadline')->nullable()->default(null);
[nits] `->default(null)` はなくても良いです

2021-05-27 08:08 UTC, ysku approved these changes
LGTM
お疲れ様でした 🎉

2021-05-27 09:40 UTC, merged